### ISSUE TITLE
Find duplicates of tracks in playlists

### ISSUE THREAD

**Issue by oscar230** [oscar230/loopbox#11]

**Comment by ZakKaioken** [comment]
I want to help with this issue. I am lost where I should find the issue at hand. Are you trying to remove duplicates? I'm lost.

**Comment by oscar230** [comment]
Thank you very much @ZakKaioken , i actually just solved it. If you would like another issue or are looking to contribute, please contact me here or at oscar.andersson.200@gmail.com. Thanks.
